#ifndef __FFCBPreferencesDialog__
#define __FFCBPreferencesDialog__

/**
@file
Subclass of PreferencesDialog, which is generated by wxFormBuilder.
*/

#include "cbgui.h"

/** Implementing PreferencesDialog */
class FFCBPreferencesDialog : public PreferencesDialog
{
protected:
	// Handlers for PreferencesDialog events.
	void OnExit( wxCloseEvent& event );
	void OnClickBrowseHex( wxCommandEvent& event );
	void OnClickOk( wxCommandEvent& event );
	void OnClickCancel( wxCommandEvent& event );
	
public:
	/** Constructor */
	FFCBPreferencesDialog( wxWindow* parent );

private:
	bool ValidData();
	void UpdateConfigs();
};

#endif // __FFCBPreferencesDialog__
