#ifndef __FFCBSingleFilePanel__
#define __FFCBSingleFilePanel__

/**
@file
Subclass of SingleFilePanel, which is generated by wxFormBuilder.
*/

#include "cbgui.h"

#include "../cblib/CBSingleFile.h"

/** Implementing SingleFilePanel */
class FFCBSingleFilePanel : public SingleFilePanel
{
protected:
	// Handlers for SingleFilePanel events.
	void OnApplyChanges( wxCommandEvent& event );
	
public:
	/** Constructor */
	FFCBSingleFilePanel( wxWindow* parent );

	void SetFile(CBSingleFile* file,wxString& fileName);

private:
	CBSingleFile* file;
	wxString fileName;
};

#endif // __FFCBSingleFilePanel__
