#ifndef __FFCBPreviewDialog__
#define __FFCBPreviewDialog__

/**
@file
Subclass of PreviewDialog, which is generated by wxFormBuilder.
*/

#include "cbgui.h"
#include "../common/common.h"

#define CHOICE_SINGLE_FILE _("Single File")
#define CHOICE_TEXT_ARCHIVE _("Text Archive")
#define CHOICE_UNKNOWN _("Unknown")

/** Implementing PreviewDialog */
class FFCBPreviewDialog : public PreviewDialog
{
protected:
	// Handlers for PreviewDialog events.
	void OnExit( wxCloseEvent& event );
	void OnPreview( wxCommandEvent& event );
	void OnOk( wxCommandEvent& event );
	void OnCancel( wxCommandEvent& event );
	
public:
	/** Constructor */
	FFCBPreviewDialog( wxWindow* parent ,wxString fileName);

	FileType GetFileType();

private:
	FileType type;
	wxString fileName;
};

#endif // __FFCBPreviewDialog__
