#ifndef __FFCBMainFrame__
#define __FFCBMainFrame__

/**
@file
Subclass of MainFrame, which is generated by wxFormBuilder.
*/

#include "FFCBFileDropHandler.h"
#include "cbgui.h"

#include "FFCBSingleFilePanel.h"
#include "FFCBTextArchivePanel.h"
#include "../common/common.h"


using namespace std;

/** Implementing MainFrame */
class FFCBMainFrame : public MainFrame, FFCBFileDropHandler
{
protected:
	// Handlers for MainFrame events.
	void OnExit( wxCloseEvent& event );
	void OnClickExit( wxCommandEvent& event );
	void OnClickOpen( wxCommandEvent& event );
	void OnClickFolder( wxCommandEvent& event );
	void OnClickFolderDb( wxCommandEvent& event );
	void OnAbout( wxCommandEvent& event );
	void OnItemClicked( wxTreeEvent& event );
	void OnClickPreferences( wxCommandEvent& event );
	
public:
	/** Constructor */
	FFCBMainFrame( wxWindow* parent );
	
	virtual void HandleFileDrop(wxString&);
private:
	//miei metodi
	FileType CheckFileType(wxString& fileName);
	void CheckAndOpenFile(wxString& fileName);
	void OpenFile(wxString& fileName,FileType type);
	FFCBSingleFilePanel* singleFilePanel;
	FFCBTextArchivePanel* archivePanel;
};

#endif // __FFCBMainFrame__
