//Copyright (C) 2010 Phoenix. 

//This program is free software: you can redistribute it and/or modify 
//it under the terms of the GNU General Public License as published by 
//the Free Software Foundation, version 2.0. 

//This program is distributed in the hope that it will be useful, 
//but WITHOUT ANY WARRANTY; without even the implied warranty of 
//MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
//GNU General Public License 2.0 for more details. 

//A copy of the GPL 2.0 should have been included with the program. 
//If not, see http://www.gnu.org/licenses/ 

//Official SVN repository and contact information can be found at 
//http://code.google.com/p/ffcbeditor/


//Copyright (C) 2010 Phoenix. 
//
//This program is free software: you can redistribute it and/or modify 
//it under the terms of the GNU General Public License as published by 
//the Free Software Foundation, version 2.0. 
//
//This program is distributed in the hope that it will be useful, 
//but WITHOUT ANY WARRANTY; without even the implied warranty of 
//MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
//GNU General Public License 2.0 for more details. 
//
//A copy of the GPL 2.0 should have been included with the program. 
//If not, see http://www.gnu.org/licenses/ 
//
//Official SVN repository and contact information can be found at 
//http://code.google.com/p/ffcbeditor/


#ifndef __FFCBPreferencesDialog__
#define __FFCBPreferencesDialog__

/**
@file
Subclass of PreferencesDialog, which is generated by wxFormBuilder.
*/

#include "cbgui.h"

/** Implementing PreferencesDialog */
class FFCBPreferencesDialog : public PreferencesDialog
{
protected:
	// Handlers for PreferencesDialog events.
	void OnExit( wxCloseEvent& event );
	void OnClickBrowseHex( wxCommandEvent& event );
	void OnClickOk( wxCommandEvent& event );
	void OnClickCancel( wxCommandEvent& event );
	
public:
	/** Constructor */
	FFCBPreferencesDialog( wxWindow* parent );

private:
	bool ValidData();
	void UpdateConfigs();
};

#endif // __FFCBPreferencesDialog__
