//Copyright (C) 2010 Phoenix. 

//This program is free software: you can redistribute it and/or modify 
//it under the terms of the GNU General Public License as published by 
//the Free Software Foundation, version 2.0. 

//This program is distributed in the hope that it will be useful, 
//but WITHOUT ANY WARRANTY; without even the implied warranty of 
//MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
//GNU General Public License 2.0 for more details. 

//A copy of the GPL 2.0 should have been included with the program. 
//If not, see http://www.gnu.org/licenses/ 

//Official SVN repository and contact information can be found at 
//http://code.google.com/p/ffcbeditor/


//Copyright (C) 2010 Phoenix. 
//
//This program is free software: you can redistribute it and/or modify 
//it under the terms of the GNU General Public License as published by 
//the Free Software Foundation, version 2.0. 
//
//This program is distributed in the hope that it will be useful, 
//but WITHOUT ANY WARRANTY; without even the implied warranty of 
//MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
//GNU General Public License 2.0 for more details. 
//
//A copy of the GPL 2.0 should have been included with the program. 
//If not, see http://www.gnu.org/licenses/ 
//
//Official SVN repository and contact information can be found at 
//http://code.google.com/p/ffcbeditor/


#ifndef __FFCBTextArchivePanel__
#define __FFCBTextArchivePanel__

/**
@file
Subclass of TextArchivePanel, which is generated by wxFormBuilder.
*/

#include "cbgui.h"
#include "../cblib/CBTextArchive.h"

/** Implementing TextArchivePanel */
class FFCBTextArchivePanel : public TextArchivePanel
{
protected:
	// Handlers for TextArchivePanel events.
	void OnPrevText( wxCommandEvent& event );
	void OnNextText( wxCommandEvent& event );
	void OnApply( wxCommandEvent& event );
	void OnSaveAll( wxCommandEvent& event );
	
public:
	/** Constructor */
	FFCBTextArchivePanel( wxWindow* parent );

	void SetEditInfo(CBTextArchive* file,size_t sectionId,wxString fileName);

private:
	CBTextArchive* file;
	size_t sectionId;
	wxString fileName;
	size_t curText;
};

#endif // __FFCBTextArchivePanel__
