//Copyright (C) 2010 Phoenix. 

//This program is free software: you can redistribute it and/or modify 
//it under the terms of the GNU General Public License as published by 
//the Free Software Foundation, version 2.0. 

//This program is distributed in the hope that it will be useful, 
//but WITHOUT ANY WARRANTY; without even the implied warranty of 
//MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
//GNU General Public License 2.0 for more details. 

//A copy of the GPL 2.0 should have been included with the program. 
//If not, see http://www.gnu.org/licenses/ 

//Official SVN repository and contact information can be found at 
//http://code.google.com/p/ffcbeditor/


#ifndef __FFCBPreviewDialog__
#define __FFCBPreviewDialog__

/**
@file
Subclass of PreviewDialog, which is generated by wxFormBuilder.
*/

#include "cbgui.h"
#include "../common/common.h"

#define CHOICE_SINGLE_FILE _("Single File")
#define CHOICE_TEXT_ARCHIVE _("Text Archive")
#define CHOICE_UNKNOWN _("Unknown")

/** Implementing PreviewDialog */
class FFCBPreviewDialog : public PreviewDialog
{
protected:
	// Handlers for PreviewDialog events.
	void OnExit( wxCloseEvent& event );
	void OnPreview( wxCommandEvent& event );
	void OnOk( wxCommandEvent& event );
	void OnCancel( wxCommandEvent& event );
	
public:
	/** Constructor */
	FFCBPreviewDialog( wxWindow* parent ,wxString fileName);

	FileType GetFileType();
private:
	FileType type;
	wxString fileName;
};

#endif // __FFCBPreviewDialog__
